{{- if .Values.imageCredentials.create -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: mediawiki-dockerhub
type: kubernetes.io/dockerconfigjson
{{- end }}
